GET http://localhost:3000/tasks?status=OPENz
###
GET http://localhost:3000/tasks/8bc19920-3518-11eb-a1de-c9af12421971
###
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "title": "",
    "description": ""
}

###
DELETE http://localhost:3000/tasks/7d0985d0-351a-11eb-b966-6920bb74512c

###
PATCH http://localhost:3000/tasks/bbedf330-3533-11eb-8e1d-2119e15e694e/status
Content-Type: application/json

{
    "status": "DONE"
}
