GET http://localhost:3000/tasks?search=js
###
GET http://localhost:3000/tasks/1
###
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "title": "Love",
    "description": "Phi Van"
}

###
DELETE http://localhost:3000/tasks/2

###
PATCH http://localhost:3000/tasks/3/status
Content-Type: application/json

{
    "status": "done"
}

###
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username": "nhan",
    "password": "123456"
}